insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Classic');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Comics');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Detactive');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Fable');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Fairy tale');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Fantasy');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Historical fiction');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Horror');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Comedy');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Mystery');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Mythology');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Science fiction');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Thriller');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Biography');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Romance');
insert into ABC_booktype (typeName_id) (select id from ABC_noveltype where novelType like 'Literature');
