# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookImage',
            field=models.FileField(default='images/logo1.png', upload_to='images/'),
        ),
    ]
