# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0002_auto_20190507_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookImage',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
