# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0007_auto_20190508_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refbooks',
            name='subjectNo',
        ),
        migrations.AddField(
            model_name='refbooks',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
